### ISSUE TITLE
Wrong docs link

### ISSUE THREAD

**Issue by GGAlanSmithee** [aiken-lang/.github#1]
The "learn in 10 minutes" link leads to https://aiken-lang.dev/which gives a 404.

**Comment by GGAlanSmithee** [comment]
PS, the project link for the core repository, https://txpipe.github.io/aiken, also leads to a 404

**Comment by rvcas** [comment]
@GGAlanSmithee thanks, we're aware, we've just moved somethings around so we'll have everything fixed soon

**Comment by rvcas** [comment]
https://aiken-lang.github.io/aiken/

**Comment by GGAlanSmithee** [comment]
Cheers @rvcas !
